#!/usr/bin/env python3

import colors as c
import random

while True:
  spaces = random.randint(1, 3)
  if spaces == 1:
    print(c.random_color() + 'ayy', end=' ' )
    print(c.random_color() + 'lmao', end=' ' )
  elif spaces == 2:
    print(c.random_color() + 'ayy', end='  ' )
    print(c.random_color() + 'lmao', end='  ' )
  elif spaces == 3:
    print(c.random_color() + 'ayy', end='   ' )
    print(c.random_color() + 'lmao', end='   ' )

