#!/usr/bin/env python3

import time
import skilstak.colors as c
from skilstak.emoji import dog

def say(animal,wait):
    print(c.multi(animal + "!"))
    time.sleep(wait)

def sing(first,second,third,count_length):
    print(c.cl + c.x, end = '')

    while True:
        for n in range(5):
            for n in range(10):
                say(first,count_length)
            for n in range(3):
                say(second,count_length * 2)
            print(c.clear, end = '')

        for n in range(2):
            say(third, count_length* 4)
        print(c.red + "Oooooh, it's a " + third + "!" + c.x)
        time.sleep(count_length * 10)
        print(c.clear, end = '')


sing("Dog" + dog,"Laaaaaa","SNAAAAAKEEEE",.2)
