#!/usr/bin/env python3

import time
import colors as c

count_length = .387
print(c.cl + c.x, end = '')
while True:
    for n in range(5):
        print(c.red + 'A badger' + c.x)
        time.sleep(count_length)
    
        for n in range(10):
            print(c.red + 'Badger!' + c.x)
            time.sleep(count_length)
        for n in range(2):
            print(c.magenta + 'Mushroom.' + c.x)
            time.sleep(count_length * 2)

        print(c.clear, end = '')

    for n in range(2):
        print(c.yellow + 'Snaaaaaakeeee!' + c.x)
        time.sleep(1.5)
    print(c.yellow + "Oooooh, it's a snaaake!" + c.x)
    time.sleep(count_length * 10)
    print(c.clear, end = '')
