#!/usr/bin/env python3

import skilstak.colors as c
print(c.clear)
import random

sides = ["1","2","3","4","5","6"]

while True:
    side = random.choice(sides)
    print(c.cyan + "You rolled a " + c.reset + c.rc() + side + c.x)
    sidecount = int(side) + sidecount
    print( c.reset + c.red + "Added up, your dice equal a total of " + c.reset + c.rc() + str(sidecount))
    input( c.reset + c.red + "Hit 'enter' to roll again.")



