#!/usr/bin/env python3

import colors as c
print(c.clear)
import random

sides = ["1","2","3","4","5","6"]

while True:
    print(c.clear)
    on = int(input(c.reset + c.cyan + "How many dice do you want to roll? "))
    print(c.clear)
    n = 1
    sidecount = 0
    while n < on or n == on:
        side = random.choice(sides)
        print(c.cyan + "You rolled a " + c.reset + c.rc() + side + c.x)
        n = n + 1
        sidecount = int(side) + sidecount
    print( c.reset + c.red + "Added up, your dice equal a total of " + c.reset + c.rc() + str(sidecount))
    input( c.reset + c.red + "Hit 'enter' to roll again.")
