#!/usr/bin/env python3

import colors as c

print( c.clear + c.yellow + "Do you like waffles?")
waffles = input("> ")

if waffles == "no" or waffles == "nah":
    print("Well, I like waffles.")

elif waffles == "yeah we like waffles" or waffles == "yeah" or waffles == "yes":
    print(c.reset + c.cyan + "Do you like pancakes?")
    pancakes = input("> ")
    if pancakes == "no" or pancakes == "nah":
        print("Well, I like pancakes.")
    elif pancakes == "yes" or pancakes == "yeah" or pancakes == "yeah we like pancakes":
        print(c.reset + c.magenta + "Do you like french toast?")
        frenchtoast = input("> ")
        if frenchtoast == "nah" or frenchtoast == "no":
            print("Well you're a nerd.")
        elif frenchtoast == "yeah" or frenchtoast == "yes" or frenchtoast == "yeah we like french toast":
            print(c.reset + c.red + "DOOT DO DO DO CAN'T WAIT TO GET A MOUTHFUL!")
        else:
            print("U w0t m8?")
    else:
        print("U w0t m8?")

else:
    print("U w0t m8?")
